# - name: "Copy {{component}} service"
#   ansible.builtin.copy:
#     src: "{{component}}.service"
#     dest: "/etc/systemd/system/{{component}}.service"

- name: "copy {{component}} service"
  ansible.builtin.template:
    src: "{{component}}.service.j2"
    dest: "/etc/systemd/system/{{component}}.service.j2"

- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "start and enable {{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes